### PR TITLE
Basic modern project setup

### LINKED ISSUE #10: Set up project structure
Follow modern Python packaging/project structure approaches and set up at least a basic initial structure to facilitate working with the project, e.g. editable pip install, dev tools (linting, type checking, testing), tox, etc.

# To Do

- [x] pyproject.toml
  - [x] [Core metadata](https://packaging.python.org/en/latest/specifications/core-metadata)
  - [x] (Optional) Dependencies
  - [x] Tool configuration (Black, isort, mypy etc.)
- [x] Package is buildable by `pip`/`setuptools`
- [x] tox.ini
  - [x] Root testenv settings
  - [x] Linter testenvs
  - [x] Build testenv
  - [x] Leverage [tox-gh plugin](https://github.com/tox-dev/tox-gh)
  - [x] Add `black --check` and `isort --check` to the lints to ensure style
  - [x] `tox devenv` target
- [x] Add new tox-based Actions workflow
- [x] Add license
- [x] Ensure `src` layout is correct with everything

### PR DESCRIPTION
**Pull request by ZeroKnight**
Resolves #10

Sets up a src-layout project structure and adds the configuration necessary to build and install the project as a package. Uses modern/emerging new standards for packages, i.e. PEP 517, 518, 621, and 660 and so can utilize a single `pyproject.toml` file for all (or at least most, currently) package metadata and tooling settings, configurable build tools, and editable project installs.

I'll briefly explain and outline each major component of this PR and what it does for the project.

# pyproject.toml

Until recently, the Python ecosystem has mostly only had a de-facto standard way to define and build packages, which would be setuptools and its `setup.py`/`setup.cfg` files. To avoid going into unnecessary detail here, [PEP 517](https://peps.python.org/pep-0517/) and [PEP 518](https://peps.python.org/pep-0518/) began to lay the groundwork for allowing projects to define in a standard way how they should be built, rather than `pip` and other tools simply assuming `setuptools`. It is in these PEPs that `pyproject.toml` was introduced, however project metadata would still be written in `setup.py`/`setup.cfg` (or whatever files the build backend expected) for the time being.

Later on, [PEP 621](https://peps.python.org/pep-0621/) officially defined `pyproject.toml` as a source for project metadata as well, i.e. what used to be written in `setup.py`/`setup.cfg`. With PEP 518 also defining a standard `[tool]` table for project tools to use as a configuration source, the culmination of these facilities makes it possible to use a single, standard source of truth for all project-related metadata and configuration instead of a having a project root with a slew of config files for various build tools, linters, formatters, and test frameworks.

This standard is somewhat recent, however, and is still evolving. Not all tools support it fully or at all, but things are constantly improving. It's made a lot of progress even since I first learned about it just a year or so ago.

## How we're using it

Our project uses `pyproject.toml` for everything mentioned above. Our build backend is defined as setuptools, project metadata is defined here, and configuration for Black, isort, and pytest are also defined here (see tox section for flake8). Since pyproject.toml supports the standard [core metadata](https://packaging.python.org/en/latest/specifications/core-metadata/), dependencies and optional dependencies can be defined there; this obviates the need for a `requirements.txt` file that only specifies top-level dependencies (they're still useful for pinning dependencies in deployments, though).

# Tox and `tox.ini`

[Tox](https://tox.wiki/en/latest/) is a project automation tool that was originally built to automate running test suites across multiple Python versions and other factors that has since evolved into a more generic virtual environment manager and tool runner, not much unlike GNU Make. Tox is extremely convenient for helping automate the Python development cycle and is flexible enough to be shaped for practically any workflow.

Once set up, tox—in a single command—can run pytest **for multiple versions of Python**, run a series of linters like `flake8`, `bandit`, etc., run `mypy` to type check the project, and perhaps even run Black and isort to format the project. All of these operations can take place in their own isolated virtual environments with only a strictly minimal set of dependencies required to perform the tasks, then aggregate the results for a final pass/fail indication. All easily repeatable as often as needed and consistent every time.

Test environments are defined in `tox.ini`; these test environments correspond to a separate virtual environment that tox manages for you, and each test environment can specify what commands to run, and what dependencies are needed to run those commands. While named "test environments", they can do anything you'd like them to. Some examples would be generating documentation, kicking off a build for a static-site generator, creating an sdist or wheel of the project, uploading a new version of the package to PyPI, and anything else you might want to do.

## How we're using it

The initial tox configuration that I've added will run `pytest`, `flake8`, and `mypy`, as well as Black and `isort` in `--check` mode. Additionally, there is a testenv for creating build artifacts (sdist and wheel) and one for setting up the development environment via `tox devenv`. While it's not specifically necessary, it makes it trivial to set up a working `venv` like so:

    $ tox devenv -e dev my_venv_name

This will create a venv in the project root named `my_venv_name` and install the project into it in **editable** mode, as well as the `[dev]` extra dependencies, which pulls in pytest, flake8, mypy, black, and isort. Editable mode makes it so that any changes to the project source code are immediately reflected in the installed package, so there is no need to reinstall it each time; just `import SoftPaqOrchestrator` and go. It's essentially a shortcut for the following:

    $ virtualenv my_venv_name  # or python -m venv my_venv_name
    $ source my_venv_name/bin/activate
    $ python -m pip install .[dev]

### flake8 configuration

Despite having pyproject.toml for tool configuration, as I mentioned, not all tools support having their configuration in pyproject.toml yet; flake8 is one such tool. It does however support sourcing its configuration from `tox.ini`, however, and so to keep in the spirit of a minimal amount of configuratiion files, I opted to do that.

### Integration with GitHub Actions

You likely noticed that tox is capable of doing a lot of what CI/GitHub Actions can do, and you'd be correct; they do indeed overlap. However, tox has the benefit of being able to run locally and on demand in its normal use, which is useful for quick feedback in the development process without having to push anything to invoke CI.

We can actually use this overlap to our advantage and use tox *within* our CI. We can avoid duplicating configuration by having CI simply install and run tox. This way we stay nice and DRY. The `tox-gh` package helps to integrate GitHub Actions with tox by mapping the Python version on Actions' side with testenvs on tox's side.

I iterated on this in my fork to avoid creating a bunch of noise in the main repo. If you'd like to see an example of a completed run using the workflow in this PR, [take a look at this](https://github.com/ZeroKnight/HP-Softpaq-Orchestrator/actions/runs/3961700705).

### Why only `--check` for Black and isort?

Regarding using `--check` mode for Black and isort and not just having tox apply those changes, in our current position, formatting automatically in our editors is easy enough, and simply checking that they've been run in CI should sufficiently enforce that.

### CODE REVIEW

**Comment by ZeroKnight** [comment]
So while I was mostly familiar with everything I've discussed here, I haven't had much actual practice implementing any of it, so there was a good bit of experimenting and reading up on things and incremental progress. Some of these commits could definitely be squashed if you'd like me to clean up the history a bit.

I also forgot to rebase this onto your CI change from a little while back, so I'll need to address that, but I'll wait until after we decide on cleaning up the history in this PR or not.

**Comment by ZeroKnight** [comment]
There are a couple of other things that I wanted to address that's related to the project as a whole, but I wasn't sure if I should tack onto this PR or make another one for them.

I [left a comment on the linked issue](https://github.com/mtsac-tech-health/HP-Softpaq-Orchestrator/issues/10#issuecomment-1387656176) about the project name. Depending on what you want to do, I could tack any resultant changes onto this PR or do so in a follow-up PR.

Second, in addition to the lints that come with flake8 out of the box, flake8 is designed to be easily extended and there are many really good lints provided by plugins out there. Would you want me to add some of them to this PR since it's already establishing flake8 configuration, or keep this one simple and add them in another PR?

**Review by rluzuriaga — APPROVED** [review]
All the changes look great and pretty straightforward. Thanks for the work!

**Comment by rluzuriaga** [comment]
@ZeroKnight Didn't realize there is a merge conflict. I'll fix that and merge the PR tomorrow.

**Comment by ZeroKnight** [comment]
> @ZeroKnight Didn't realize there is a merge conflict. I'll fix that and merge the PR tomorrow.

Yeah, I forgot to rebase on top of that CI change that you made. Let me know if you'd like me to squash any of the history down before-hand; some of the commits are sort of obviated by later ones. Or just go for it if you're okay with it as-is. 😄

**Pull request merged**
